import { useEffect, useMemo, useState } from 'react';
import {
  Folder,
  FolderOpen,
  FileText,
  Sparkles,
  Brain,
  Search,
  ChevronRight,
  Lock,
  Loader2,
  RefreshCw,
} from 'lucide-react';
import { clsx } from 'clsx';
import { useStore } from '@/core/store';
import {
  subscribeKampsparEntries,
  subscribeKbDocsEntries,
} from '@/core/firebase/firestore';
import type { KampsparEntryRow, KbDocEntryRow } from '@/core/types/firestore';
import {
  mapFlatRowsToArchiveTree,
  countArchiveFiles,
  defaultExpandedFolderIds,
  filterArchiveTree,
  type ArchiveNode,
} from '../utils/buildArchiveTree';

const MAX_EXPANDED_FOLDERS = 3;

type AutonomousArchivePanelProps = {
  /** Delad kampspar-lista från KunskapPage — undviker dubbel Firestore-prenumeration. */
  sharedKampspar?: KampsparEntryRow[];
};

export function AutonomousArchivePanel({ sharedKampspar }: AutonomousArchivePanelProps) {
  const user = useStore((s) => s.user);
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set());
  const [kampspar, setKampspar] = useState<KampsparEntryRow[]>([]);
  const [kbDocs, setKbDocs] = useState<KbDocEntryRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [initializedExpand, setInitializedExpand] = useState(false);

  useEffect(() => {
    if (sharedKampspar) setKampspar(sharedKampspar);
  }, [sharedKampspar]);

  // Real-time Kunskap-silo: kampspar + kb_docs (ingen mock-data).
  useEffect(() => {
    if (!user) {
      setKampspar([]);
      setKbDocs([]);
      setLoading(false);
      setError(null);
      setInitializedExpand(false);
      setExpandedFolders(new Set());
      return;
    }

    setLoading(true);
    setError(null);
    let kampsparReady = false;
    let kbReady = false;

    const maybeDone = () => {
      if (kampsparReady && kbReady) setLoading(false);
    };

    let unsubKampspar: (() => void) | undefined;
    if (sharedKampspar) {
      kampsparReady = true;
      maybeDone();
    } else {
      unsubKampspar = subscribeKampsparEntries(
        user.uid,
        (rows) => {
          setKampspar(rows);
          kampsparReady = true;
          maybeDone();
        },
        () => {
          setError('Kunde inte läsa kampspar.');
          kampsparReady = true;
          maybeDone();
        },
      );
    }

    const unsubKb = subscribeKbDocsEntries(
      user.uid,
      (rows) => {
        setKbDocs(rows);
        kbReady = true;
        maybeDone();
      },
      () => {
        setError('Kunde inte läsa kb_docs.');
        kbReady = true;
        maybeDone();
      },
    );

    return () => {
      unsubKampspar?.();
      unsubKb();
    };
  }, [user, sharedKampspar != null]);

  const archiveTree = useMemo(
    () => mapFlatRowsToArchiveTree(kampspar, kbDocs),
    [kampspar, kbDocs],
  );

  useEffect(() => {
    if (initializedExpand || archiveTree.length === 0) return;
    setExpandedFolders(new Set(defaultExpandedFolderIds(archiveTree, 2)));
    setInitializedExpand(true);
  }, [archiveTree, initializedExpand]);

  const filteredTree = useMemo(
    () => filterArchiveTree(archiveTree, searchQuery),
    [archiveTree, searchQuery],
  );

  const totalFiles = useMemo(() => countArchiveFiles(archiveTree), [archiveTree]);

  const toggleFolder = (id: string) => {
    setExpandedFolders((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
        return next;
      }
      if (next.size >= MAX_EXPANDED_FOLDERS) {
        const [first] = next;
        if (first) next.delete(first);
      }
      next.add(id);
      return next;
    });
  };

  const renderTree = (nodes: ArchiveNode[], depth = 0) => {
    if (depth >= 3) return null;

    return (
      <ul className={clsx('space-y-1.5', depth > 0 && 'ml-4 mt-1.5 border-l border-border/30 pl-3')}>
        {nodes.map((node) => {
          const isExpanded = expandedFolders.has(node.id) || Boolean(searchQuery.trim());

          if (node.type === 'folder') {
            return (
              <li key={node.id}>
                <button
                  type="button"
                  onClick={() => toggleFolder(node.id)}
                  className="group flex w-full items-center justify-between rounded-lg p-2 transition-colors hover:bg-surface-3/50"
                >
                  <div className="flex items-center gap-2">
                    {isExpanded ? (
                      <FolderOpen className="h-4 w-4 text-accent" />
                    ) : (
                      <Folder className="h-4 w-4 text-accent/70 transition-colors group-hover:text-accent" />
                    )}
                    <span className="text-sm font-medium text-text">{node.title}</span>
                    {node.isAutoGenerated && (
                      <span title="Mapp auto-skapad av AI" aria-hidden>
                        <Sparkles className="ml-1 h-3 w-3 text-indigo-400 opacity-60" />
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    {node.count != null && (
                      <span className="rounded-md bg-surface-3 px-1.5 py-0.5 text-[10px] text-text-dim">
                        {node.count}
                      </span>
                    )}
                    <ChevronRight
                      className={clsx(
                        'h-3.5 w-3.5 text-text-dim transition-transform duration-200',
                        isExpanded && 'rotate-90',
                      )}
                    />
                  </div>
                </button>
                {isExpanded && node.children && renderTree(node.children, depth + 1)}
              </li>
            );
          }

          return (
            <li key={node.id}>
              <button
                type="button"
                className="group flex w-full items-start gap-2 rounded-lg p-2 text-left transition-colors hover:bg-surface-3/50"
              >
                <FileText className="mt-0.5 h-3.5 w-3.5 shrink-0 text-text-muted transition-colors group-hover:text-text" />
                <div>
                  <span className="line-clamp-1 text-xs text-text-muted transition-colors group-hover:text-text">
                    {node.title}
                  </span>
                  {(node.date || node.excerpt) && (
                    <div className="mt-0.5 flex items-center gap-2">
                      {node.date && <span className="text-[9px] text-text-dim">{node.date}</span>}
                      {node.excerpt && (
                        <span className="max-w-[150px] truncate text-[9px] text-text-dim">
                          — {node.excerpt}
                        </span>
                      )}
                    </div>
                  )}
                </div>
              </button>
            </li>
          );
        })}
      </ul>
    );
  };

  return (
    <div className="rounded-2xl border border-border/40 bg-surface/40 p-1 shadow-sm backdrop-blur-md">
      <div className="flex items-start justify-between rounded-t-xl border-b border-border/30 bg-surface-2 p-4 sm:p-5">
        <div>
          <h2 className="flex items-center gap-2 text-sm font-bold text-accent">
            <Brain className="h-4 w-4" />
            Det Självbyggande Arkivet
          </h2>
          <p className="mt-1 max-w-md text-xs leading-relaxed text-text-muted">
            Allt du kastar in i appen sorteras och systematiseras här automatiskt under natten. Du
            behöver aldrig skapa en mapp.
          </p>
        </div>
        <div className="flex items-center gap-1.5 rounded-md border border-indigo-500/20 bg-indigo-500/10 px-2 py-1">
          <Sparkles className="h-3 w-3 text-indigo-400" />
          <span className="text-[10px] font-medium uppercase tracking-widest text-indigo-300">
            Auto-Organiserad
          </span>
        </div>
      </div>

      <div className="flex min-h-[300px] flex-col gap-4 p-4 sm:p-5">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-text-dim" />
          <input
            type="search"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Sök i hela din kunskapsbank..."
            className="w-full rounded-xl border border-border/50 bg-surface-2 py-2.5 pl-9 pr-4 text-xs text-text transition-colors focus:border-accent focus:outline-none"
          />
        </div>

        {!user && (
          <p className="py-8 text-center text-xs text-text-dim">Logga in för att se ditt arkiv.</p>
        )}

        {user && loading && (
          <div className="flex items-center justify-center gap-2 py-8 text-xs text-text-muted">
            <Loader2 className="h-4 w-4 animate-spin text-accent" />
            Hämtar arkivstruktur…
          </div>
        )}

        {user && error && !loading && (
          <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 px-4 py-3 text-xs text-amber-200/90">
            <div className="flex items-center gap-2">
              <RefreshCw className="h-3.5 w-3.5 shrink-0" />
              {error}
            </div>
          </div>
        )}

        {user && !loading && (
          <div className="custom-scrollbar flex-1 overflow-y-auto pr-2">
            {filteredTree.length > 0 ? (
              renderTree(filteredTree)
            ) : (
              <p className="py-8 text-center text-xs text-text-dim">
                {searchQuery.trim()
                  ? 'Inga träffar i arkivet.'
                  : 'Arkivet är tomt — inkast och uppladdningar hamnar här automatiskt.'}
              </p>
            )}
          </div>
        )}

        <div className="flex items-center justify-between border-t border-border/30 pt-3 text-[10px] text-text-dim">
          <span className="flex items-center gap-1">
            <Lock className="h-3 w-3" /> Krypterat och lokalt indexerat.
          </span>
          <span>Totalt {totalFiles} filer</span>
        </div>
      </div>
    </div>
  );
}
