import type { DfNotis } from './dfBankTypes';

export const DF_NOTIS_BANK: readonly DfNotis[] = [

  { id: 'DF-NOTIS-01', text_sv: 'Ett ankare finns här.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-02', text_sv: 'En dag i taget — börja med nästa timme.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-03', text_sv: 'Du behöver inte agera på suget.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-04', text_sv: 'HALT: hungrig, arg, ensam, trött?', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-05', text_sv: 'Vatten. Andning. Ett steg.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-06', text_sv: 'Quiet hours skyddar dig — inte straffar.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-07', text_sv: 'Öppna SOS om det känns tungt.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-08', text_sv: 'Du har verktyg. Ett räcker.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-09', text_sv: 'Vänta femton minuter med köpet.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-10', text_sv: 'Sug är en våg.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-11', text_sv: 'Mikrosteg räcker idag.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-12', text_sv: 'Du är inte ensam om detta.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-13', text_sv: 'Kroppen först.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-14', text_sv: 'Ett värdeord — sen handling.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-15', text_sv: 'Stödlinjer finns under Stöd.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-16', text_sv: 'Natten går. Ankaret finns.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-17', text_sv: 'Ingen streak. Bara nästa val.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-18', text_sv: 'Du får be om hjälp.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-19', text_sv: 'Delay är okej.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-20', text_sv: 'Landning > kamp.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-21', text_sv: 'Ett andetag.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-22', text_sv: 'Du klarade en våg förr.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-23', text_sv: 'Öppna planen om du vill.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-24', text_sv: 'Ingen skam. Bara verktyg.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-25', text_sv: 'Här och nu.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-26', text_sv: 'Välj det enklaste verktyget.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-27', text_sv: 'Du bygger riktning.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-28', text_sv: 'Check-in med dig själv — mjukt.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-29', text_sv: 'Impuls kan vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-30', text_sv: 'Du är här. Det räcker som start.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-31', text_sv: 'Öppna SOS om vågen växer.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-32', text_sv: 'Ett ankare. En minut.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-33', text_sv: 'Quiet hours skyddar dig.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-34', text_sv: 'Du får vänta ut suget.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-35', text_sv: 'Vatten först.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-36', text_sv: 'HALT-check tar tre sekunder.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-37', text_sv: 'Mikrosteg räcker.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-38', text_sv: 'Ring trygg person om du vill.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-39', text_sv: 'Ingen skam i verktyg.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-40', text_sv: 'Du bygger riktning.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-41', text_sv: 'Landning före beslut.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-42', text_sv: 'Sug är tillfälligt.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-43', text_sv: 'Anti-köp: vänta kvart.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-44', text_sv: 'Andas ut längre.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-45', text_sv: 'Du är mer än impulsen.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-46', text_sv: 'Planen finns under Idag.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-47', text_sv: 'Buddy kan få ett SMS.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-48', text_sv: 'Nattbeslut kan vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-49', text_sv: 'Ett värdeord — sen steg.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-50', text_sv: 'Du klarade en våg förr.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-51', text_sv: 'Här och nu.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-52', text_sv: 'Stödlinjer under Stöd.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-53', text_sv: 'Ingen streak. Bara val.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-54', text_sv: 'Kom tillbaka mjukt.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-55', text_sv: 'Fötterna i golvet.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-56', text_sv: 'Ljus på. Rumbyte.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-57', text_sv: 'Du får be om hjälp.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-58', text_sv: 'Timer på tre.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-59', text_sv: 'Spara stora beslut till dag.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-60', text_sv: 'Ankare finns.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-61', text_sv: 'Du behöver inte agera.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-62', text_sv: 'En mening till dig: jag stannar.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-63', text_sv: 'Kropp först.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-64', text_sv: 'Skärm ner. Andning upp.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-65', text_sv: 'Du har verktyg.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-66', text_sv: 'Mjuk riktning.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-67', text_sv: 'Vänta. Andas. Välj.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-68', text_sv: 'Det går över.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-69', text_sv: 'Öppna planen om du vill.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-70', text_sv: 'Trygg kontakt finns.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-71', text_sv: 'Ingen jakt. Bara stöd.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-72', text_sv: 'Du får landa.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-73', text_sv: 'Ett steg. Inte alla.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-74', text_sv: 'Suget ljuger om brådska.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-75', text_sv: 'Välj det enklaste.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-76', text_sv: 'Du är här. Bra start.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-77', text_sv: 'Skydd, inte straff.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-78', text_sv: 'Imorgon är ett nytt fönster.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-79', text_sv: 'Håll i ankaret.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-80', text_sv: 'Du får säga nej mjukt.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-81', text_sv: 'Riktningsval, inte perfektion.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-82', text_sv: 'SOS Ankare finns.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-83', text_sv: 'Check-in utan krav.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-84', text_sv: 'Du är kapabel.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-85', text_sv: 'Nästa timme. Inte hela livet.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-86', text_sv: 'Lugn röst till dig själv.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-87', text_sv: 'Verktyg före impuls.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-88', text_sv: 'Du får pausa.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-89', text_sv: 'Stanna. Andas. Välj.', evidence_tier: 'product_copy' },
  { id: 'DF-NOTIS-90', text_sv: 'Det finns en väg tillbaka.', evidence_tier: 'product_copy' },
];

export const DF_NOTIS_COUNT = 90 as const;
