import { sanitizeDfBankText, type DfQuote } from './dfBankTypes';
export const DF_QUOTE_BANK: readonly DfQuote[] = [

  { id: 'DF-QUOTE-VAG-01', category: 'vag', text_sv: 'Sug är en våg. Den toppar och sjunker.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-02', category: 'vag', text_sv: 'Du behöver inte följa vågen — bara se den.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-03', category: 'vag', text_sv: 'Det här känns starkt. Det är tillfälligt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-04', category: 'vag', text_sv: 'Namnge: sug. Det är inte ett kommando.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-05', category: 'vag', text_sv: 'Vågor går över. Du kan vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-06', category: 'vag', text_sv: 'Intensiteten är information, inte dom.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-07', category: 'vag', text_sv: 'Andas med känslan — inte emot den.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-08', category: 'vag', text_sv: 'Ett andetag. Sen ett till.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-09', category: 'vag', text_sv: 'Du surfar. Du behöver inte vinna.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-10', category: 'vag', text_sv: 'Sug får finnas utan att du följer det.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-11', category: 'vag', text_sv: 'Toppen kommer. Sen sjunker det.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VAG-12', category: 'vag', text_sv: 'Du klarade en våg tidigare. Du kan igen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-01', category: 'halt', text_sv: 'Hungrig? Ät först. Bestäm sen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-02', category: 'halt', text_sv: 'Arg? Rörelse före beslut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-03', category: 'halt', text_sv: 'Ensam? Ett kort meddelande räcker.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-04', category: 'halt', text_sv: 'Trött? Vila. Minska beslut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-05', category: 'halt', text_sv: 'HALT först — substans senare aldrig.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-06', category: 'halt', text_sv: 'Kroppen skriker. Fråga vad den behöver.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-07', category: 'halt', text_sv: 'Mat, vatten, ljus — enkla steg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-08', category: 'halt', text_sv: 'Trötthet är inte misslyckande.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-09', category: 'halt', text_sv: 'Ensamhet vill kontakt, inte rus.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-10', category: 'halt', text_sv: 'Ilska vill utrymme, inte köp.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-11', category: 'halt', text_sv: 'Checka HALT innan du öppnar plånboken.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-12', category: 'halt', text_sv: 'Ett behov i taget. Börja med kroppen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-01', category: 'varde', text_sv: 'Ett värdeord idag: vad vill du stå för?', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-02', category: 'varde', text_sv: 'Nykterhet som medel — inte straff.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-03', category: 'varde', text_sv: 'Pappa. Klarhet. Hälsa. Välj ett.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-04', category: 'varde', text_sv: 'Du bygger riktning, inte perfektion.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-05', category: 'varde', text_sv: 'Vad betyder mest de närmaste timmarna?', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-06', category: 'varde', text_sv: 'Värdet finns kvar även när suget finns.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-07', category: 'varde', text_sv: 'Små handlingar i rätt riktning räcker.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-08', category: 'varde', text_sv: 'Du väljer — du är inte din impuls.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-09', category: 'varde', text_sv: 'Frihet börjar med nästa beslut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-10', category: 'varde', text_sv: 'Trygghet för dig är också trygghet för andra.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-11', category: 'varde', text_sv: 'Ett steg i värderiktning är nog.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-VARD-12', category: 'varde', text_sv: 'Du får unna dig återhämtning utan skuld.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-01', category: 'delay', text_sv: 'Beslutet kan vänta femton minuter.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-02', category: 'delay', text_sv: 'Plånboken kan stanna. Du kan vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-03', category: 'delay', text_sv: 'Delay är styrka, inte svaghet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-04', category: 'delay', text_sv: 'Sätt en timer. Gör något annat.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-05', category: 'delay', text_sv: 'Om suget finns kvar om en kvart — öppna ankaret.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-06', category: 'delay', text_sv: 'Du behöver inte köpa nu.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-07', category: 'delay', text_sv: 'Vänta. Andas. Sen utvärdera.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-08', category: 'delay', text_sv: 'Impuls älskar hastighet. Du saktar ner.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-09', category: 'delay', text_sv: 'Ett nej till köp är ett ja till dig.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-10', category: 'delay', text_sv: 'Femton minuter — det är allt du lovar dig.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-11', category: 'delay', text_sv: 'Byt rum innan du byter beslut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-DELA-12', category: 'delay', text_sv: 'Delay först. Handling sen — med huvudet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-01', category: 'kropp', text_sv: 'Kallt vatten på handlederna.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-02', category: 'kropp', text_sv: 'Drick vatten. Sätt dig.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-03', category: 'kropp', text_sv: 'Gå ut två minuter — ingen destination.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-04', category: 'kropp', text_sv: 'Andas lugnt. Räkna inte om det stör.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-05', category: 'kropp', text_sv: 'Kroppen kan landa utan rus.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-06', category: 'kropp', text_sv: 'Sträck dig. Rör axlarna.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-07', category: 'kropp', text_sv: 'Duscha ansiktet. Börja om.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-08', category: 'kropp', text_sv: 'Tyngd i fötterna. Här och nu.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-09', category: 'kropp', text_sv: 'Mat i magen hjälper impulskontroll.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-10', category: 'kropp', text_sv: 'Sömn är skydd — inte lyx.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-11', category: 'kropp', text_sv: 'Ljus. Luft. Rörelse.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-KROP-12', category: 'kropp', text_sv: 'Kroppen först. Tankar sen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-01', category: 'antikop', text_sv: 'Köpet kan vänta. Du också.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-02', category: 'antikop', text_sv: 'Pengarna stannar. Du stannar.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-03', category: 'antikop', text_sv: 'Anti-köp är ett konkret nej just nu.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-04', category: 'antikop', text_sv: 'Öppna inte appen som säljer. Öppna ankaret.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-05', category: 'antikop', text_sv: 'Ett köp löser inte det här behovet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-06', category: 'antikop', text_sv: 'Vänta. Du förlorar inte på att vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-07', category: 'antikop', text_sv: 'Stäng kanalen till köp i femton minuter.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-08', category: 'antikop', text_sv: 'Du har klarat nej förut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-09', category: 'antikop', text_sv: 'Köpet är inte den enda utvägen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-10', category: 'antikop', text_sv: 'Skriv: jag väntar. Sen andas.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-11', category: 'antikop', text_sv: 'Plånbok stängd. Ankare öppet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANTI-12', category: 'antikop', text_sv: 'Det här är impuls. Inte nödvändighet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-01', category: 'lapse', text_sv: 'Ett steg ur spår är inte hela resan.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-02', category: 'lapse', text_sv: 'Lapse ≠ dig som person.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-03', category: 'lapse', text_sv: 'Skam hjälper inte. Nästa timme gör det.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-04', category: 'lapse', text_sv: 'Du är tillbaka. Det räcker som start.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-05', category: 'lapse', text_sv: 'AVE: skam kan trigga mer — bryt den.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-06', category: 'lapse', text_sv: 'Nollställ utan straff. Börja om mjukt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-07', category: 'lapse', text_sv: 'Vad lärde kroppen — utan etikett?', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-08', category: 'lapse', text_sv: 'Kom tillbaka. Du får det.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-09', category: 'lapse', text_sv: 'Ett slip säger inte att allt är förstört.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-10', category: 'lapse', text_sv: 'Aktivera planen. Inte skammen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-11', category: 'lapse', text_sv: 'Nästa 24 timmar räknas.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-LAPS-12', category: 'lapse', text_sv: 'Du bygger vidare — inte om från skuld.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-01', category: 'ensamhet', text_sv: 'Ensamhet vill kontakt. Ett meddelande.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-02', category: 'ensamhet', text_sv: 'Du behöver inte förklara allt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-03', category: 'ensamhet', text_sv: 'Ring eller skriv: behöver check-in.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-04', category: 'ensamhet', text_sv: 'Närvaro räcker — perfekt chatt krävs inte.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-05', category: 'ensamhet', text_sv: 'Isolering ljuger. Du är inte ensam om detta.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-06', category: 'ensamhet', text_sv: 'Öppna Stöd-flik. Välj en linje.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-07', category: 'ensamhet', text_sv: 'Ett namn. Ett hej. Det räcker.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-08', category: 'ensamhet', text_sv: 'Ensamhet är en signal, inte en dom.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-09', category: 'ensamhet', text_sv: 'Droghjälpen finns om du vill vara anonym.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-10', category: 'ensamhet', text_sv: 'Du får be om hjälp utan att be om ursäkt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-11', category: 'ensamhet', text_sv: 'Kort kontakt bryter spiralen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ENSA-12', category: 'ensamhet', text_sv: 'Sitt med dig själv — men inte utan verktyg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-01', category: 'adhd', text_sv: 'Ett steg. Inte hela listan.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-02', category: 'adhd', text_sv: 'Mikrosteg vinner över perfektion.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-03', category: 'adhd', text_sv: 'Impuls är snabb. Du tar 2 minuter.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-04', category: 'adhd', text_sv: 'ADHD-hjärna: kropp först, beslut sen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-05', category: 'adhd', text_sv: 'Minska val. Öppna bara ankaret.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-06', category: 'adhd', text_sv: 'Timer hjälper — utan skräck-countdown.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-07', category: 'adhd', text_sv: 'Du behöver inte orka allt. Bara nästa.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-08', category: 'adhd', text_sv: 'Struktur är vänlighet, inte krav.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-09', category: 'adhd', text_sv: 'Trötthet + impuls = vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-10', category: 'adhd', text_sv: 'Gör det lilla. Sen paus.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-11', category: 'adhd', text_sv: 'En skärm. Ett jobb.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-12', category: 'adhd', text_sv: 'Du får välja det enklaste verktyget.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-01', category: 'natt', text_sv: 'Natt suger mer. Det är vanligt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-02', category: 'natt', text_sv: 'Mörker höjer risk — ankaret finns.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-03', category: 'natt', text_sv: 'Sov om du kan. Annars: vatten och ljus.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-04', category: 'natt', text_sv: 'Nattköp kan vänta till morgonen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-05', category: 'natt', text_sv: 'Du behöver inte lösa natten med rus.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-06', category: 'natt', text_sv: 'Quiet hours: skydd, inte straff.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-07', category: 'natt', text_sv: 'Imorgon är ett nytt fönster.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-08', category: 'natt', text_sv: 'Låg belysning. Lugn röst till dig själv.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-09', category: 'natt', text_sv: 'Natten går. Du kan hålla dig.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-10', category: 'natt', text_sv: 'Om suget toppar nu — urge surf två minuter.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-11', category: 'natt', text_sv: 'Lägg dig om du kan. Annars: jordning.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-12', category: 'natt', text_sv: 'Du klarade nätter förr. En till.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-13', category: 'ankare', text_sv: 'Ankaret är ett val, inte ett bevis.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-14', category: 'ankare', text_sv: 'Du får landa innan du tänker.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-15', category: 'ankare', text_sv: 'Håll i det enklaste verktyget.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-16', category: 'ankare', text_sv: 'Ett ankare räcker för den här minuten.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-17', category: 'ankare', text_sv: 'Stabilitet först. Ord senare.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-18', category: 'ankare', text_sv: 'Du behöver inte prestera dig ur suget.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-19', category: 'ankare', text_sv: 'Trygghet är en handling, inte en känsla.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-20', category: 'ankare', text_sv: 'Låt kroppen leda en stund.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-21', category: 'ankare', text_sv: 'Du får pausa utan att ge upp.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-22', category: 'ankare', text_sv: 'Ankare = närvaro, inte straff.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-23', category: 'ankare', text_sv: 'Det finns en väg tillbaka till dig.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-24', category: 'ankare', text_sv: 'Här är tillräckligt bra just nu.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-25', category: 'ankare', text_sv: 'Du bygger trygghet i små steg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-26', category: 'ankare', text_sv: 'Ett andetag är en riktning.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-27', category: 'ankare', text_sv: 'Du får vara mjuk mot dig själv.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-28', category: 'ankare', text_sv: 'Landning före beslut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-29', category: 'ankare', text_sv: 'Du är mer än suget.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-30', category: 'ankare', text_sv: 'Verktyg finns. Använd ett.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-31', category: 'ankare', text_sv: 'Ingen tävling. Bara nästa steg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ANK-32', category: 'ankare', text_sv: 'Du får välja långsamt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-13', category: 'urge', text_sv: 'Suget stiger och faller — som väder.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-14', category: 'urge', text_sv: 'Du behöver inte följa impulsen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-15', category: 'urge', text_sv: 'Vänta ut toppen. Den går över.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-16', category: 'urge', text_sv: 'Observera suget utan att agera.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-17', category: 'urge', text_sv: 'Namnge det: det är en våg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-18', category: 'urge', text_sv: 'Femton minuter kan ändra allt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-19', category: 'urge', text_sv: 'Impuls är snabb. Du får vara långsam.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-20', category: 'urge', text_sv: 'Suget ljuger om brådska.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-21', category: 'urge', text_sv: 'Du har klarat vågor förr.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-22', category: 'urge', text_sv: 'Andas ut längre än in.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-23', category: 'urge', text_sv: 'Flytta kroppen. Byt rum.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-24', category: 'urge', text_sv: 'Drick vatten. Sen bestäm.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-25', category: 'urge', text_sv: 'Skjut upp köpet en kvart.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-26', category: 'urge', text_sv: 'Suget är information, inte order.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-27', category: 'urge', text_sv: 'Du får säga nej till dig själv mjukt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-28', category: 'urge', text_sv: 'Räkna andetag till tio.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-29', category: 'urge', text_sv: 'Det här är tillfälligt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-30', category: 'urge', text_sv: 'Du styr händerna. Inte suget.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-31', category: 'urge', text_sv: 'Våga vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-URG-32', category: 'urge', text_sv: 'Urge surf: känn, andas, stanna.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-13', category: 'halt', text_sv: 'Hungrig? Ät något enkelt först.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-14', category: 'halt', text_sv: 'Arg? Pausa kontakten en stund.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-15', category: 'halt', text_sv: 'Ensam? Ring en trygg röst.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-16', category: 'halt', text_sv: 'Trött? Vila före beslut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-17', category: 'halt', text_sv: 'HALT är en checklista, inte skuld.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-18', category: 'halt', text_sv: 'Kolla kroppen innan du köper.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-19', category: 'halt', text_sv: 'Sömnbrist höjer risk — planera mjukt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-20', category: 'halt', text_sv: 'Mat + vatten löser mer än du tror.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-21', category: 'halt', text_sv: 'Ilska vill ha snabb fix. Vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-22', category: 'halt', text_sv: 'Ensamhet söker sällskap — välj tryggt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-23', category: 'halt', text_sv: 'Trötthet förvränger val.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-24', category: 'halt', text_sv: 'HALT först. Handling sen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-25', category: 'halt', text_sv: 'Du får ta hand om basbehoven.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-26', category: 'halt', text_sv: 'Kropp i balans = klarare val.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-27', category: 'halt', text_sv: 'Små behov, stora konsekvenser.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-28', category: 'halt', text_sv: 'Fyll på innan du töms.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-29', category: 'halt', text_sv: 'Vilken HALT-del skriker högst?', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-30', category: 'halt', text_sv: 'En punkt i taget.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-31', category: 'halt', text_sv: 'Du förtjänar baskomfort.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-HALT-32', category: 'halt', text_sv: 'Bas först. Resten senare.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-13', category: 'adhd', text_sv: 'En sak. En skärm. En minut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-14', category: 'adhd', text_sv: 'Byt uppgift till något litet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-15', category: 'adhd', text_sv: 'Timer på tre minuter — sen omvärdera.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-16', category: 'adhd', text_sv: 'ADHD-hjärnan vill allt nu. Du får välja ett.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-17', category: 'adhd', text_sv: 'Stimulans kan vara promenad, inte rus.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-18', category: 'adhd', text_sv: 'Skriv ner impulsen. Låt den ligga.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-19', category: 'adhd', text_sv: 'Dopamin från rörelse är okej.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-20', category: 'adhd', text_sv: 'Förkorta beslutet till ja/nej på verktyget.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-21', category: 'adhd', text_sv: 'Du får externa ankare (lapp, alarm).', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-22', category: 'adhd', text_sv: 'Överstimulering? Sänk ljudet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-23', category: 'adhd', text_sv: 'Mikro-seger: öppna SOS.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-24', category: 'adhd', text_sv: 'Du behöver inte hålla allt i huvudet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-25', category: 'adhd', text_sv: 'Struktur sparar energi.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-26', category: 'adhd', text_sv: 'Byt miljö innan du byter beslut.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-27', category: 'adhd', text_sv: 'ADHD + sug = hög fart. Bromsa mjukt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-28', category: 'adhd', text_sv: 'Ett objekt i handen. Sen andetag.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-29', category: 'adhd', text_sv: 'Du får be om påminnelser.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-30', category: 'adhd', text_sv: 'Korta fönster. Tydliga steg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-31', category: 'adhd', text_sv: 'Rensa synfältet. En sak kvar.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-ADHD-32', category: 'adhd', text_sv: 'Din hjärna är snabb — planen får vara långsam.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-13', category: 'natt', text_sv: 'Nattbeslut kan vänta till gryning.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-14', category: 'natt', text_sv: 'Ljus på. Telefon bort från köp.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-15', category: 'natt', text_sv: 'Natten överdriver. Morgonen förtydligar.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-16', category: 'natt', text_sv: 'Om du är vaken: vatten + stretch.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-17', category: 'natt', text_sv: 'Ingen nattbeställning. Punkt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-18', category: 'natt', text_sv: 'Lägg dig om du kan. Annars: jordning.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-19', category: 'natt', text_sv: 'Nattens sug är ofta trötthet i förklädnad.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-20', category: 'natt', text_sv: 'Tyst röst. Långsam andning.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-21', category: 'natt', text_sv: 'Du behöver inte vinna natten. Bara överleva den.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-22', category: 'natt', text_sv: 'Skärmljus lågt. Beslut senare.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-23', category: 'natt', text_sv: 'Ring ingen som triggar. Ring trygg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-24', category: 'natt', text_sv: 'Nattköp = morgonånger. Vänta.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-25', category: 'natt', text_sv: 'Lägg telefonen i annat rum.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-26', category: 'natt', text_sv: 'Du har en plan för morgonens första steg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-27', category: 'natt', text_sv: 'Mörker går över. Du också.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-28', category: 'natt', text_sv: 'Om du skakar: kallt vatten i ansiktet.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-29', category: 'natt', text_sv: 'Natten är tillfällig. Valet är ditt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-30', category: 'natt', text_sv: 'Spara stora beslut till dagsljus.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-31', category: 'natt', text_sv: 'Du får sova dig förbi vågen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-NATT-32', category: 'natt', text_sv: 'Ankare i mörkret finns.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-13', category: 'comeback', text_sv: 'En snedsteg raderar inte dig.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-14', category: 'comeback', text_sv: 'Kom tillbaka utan skamteater.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-15', category: 'comeback', text_sv: 'Nästa val räknas mer än gårdagen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-16', category: 'comeback', text_sv: 'AVE: lär, justera, fortsätt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-17', category: 'comeback', text_sv: 'Du får börja om mjukt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-18', category: 'comeback', text_sv: 'Återkomst är styrka, inte nederlag.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-19', category: 'comeback', text_sv: 'Räkna framåt, inte bakåt.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-20', category: 'comeback', text_sv: 'Planen finns. Använd den igen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-21', category: 'comeback', text_sv: 'Skuld hjälper inte. Verktyg gör.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-22', category: 'comeback', text_sv: 'Du är fortfarande kapabel.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-23', category: 'comeback', text_sv: 'En timme nykter är ett steg.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-24', category: 'comeback', text_sv: 'Ingen streak krävs för värde.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-25', category: 'comeback', text_sv: 'Berätta för dig själv: jag är här igen.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-26', category: 'comeback', text_sv: 'Små reparationer räcker.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-27', category: 'comeback', text_sv: 'Du får be om hjälp efter en lapse.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-28', category: 'comeback', text_sv: 'Kartlägg triggern. Inte dig själv som fel.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-29', category: 'comeback', text_sv: 'Komback-bannern finns av en anledning.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-30', category: 'comeback', text_sv: 'Du bygger riktning, inte perfektion.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-31', category: 'comeback', text_sv: 'Idag är ett nytt fönster.', evidence_tier: 'product_copy' },
  { id: 'DF-QUOTE-CB-32', category: 'comeback', text_sv: 'Välkommen tillbaka till dig.', evidence_tier: 'product_copy' },
];

export const DF_QUOTE_COUNT = 240 as const;

export function dfQuoteDisplayText(q: DfQuote): string {
  return sanitizeDfBankText(q.text_sv);
}
