import { sanitizeDfBankText, type DfQuestion } from './dfBankTypes';
export const DF_QUESTION_BANK: readonly DfQuestion[] = [

  { id: 'DF-Q-TRI-01', bucket: 'trigger', text_sv: 'Vad hände precis innan suget — plats, tid, känsla?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-02', bucket: 'trigger', text_sv: 'Vilken tid på dygnet är risken högst för dig?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-03', bucket: 'trigger', text_sv: 'Vilken plats vill du undvika idag?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-04', bucket: 'trigger', text_sv: 'Vilken person/situation höjer risken?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-05', bucket: 'trigger', text_sv: 'Vad triggade senast — utan att döma dig?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-06', bucket: 'trigger', text_sv: 'Var det extern trigger eller inre (känsla)?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-07', bucket: 'trigger', text_sv: 'Vad såg, hörde eller luktade du precis innan?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-08', bucket: 'trigger', text_sv: 'Fanns det ett “bara denna gång”-argument?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-09', bucket: 'trigger', text_sv: 'Vilken app eller sak är kopplad till risk?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-TRI-10', bucket: 'trigger', text_sv: 'Vad var det första tecknet i kroppen?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-01', bucket: 'kansla', text_sv: 'Vilket behov försökte suget lösa?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-02', bucket: 'kansla', text_sv: 'Är du hungrig, arg, ensam eller trött?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-03', bucket: 'kansla', text_sv: 'Vilken känsla är starkast just nu — ett ord?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-04', bucket: 'kansla', text_sv: 'Var i kroppen sitter det?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-05', bucket: 'kansla', text_sv: 'Vad skulle du säga till en vän i samma läge?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-06', bucket: 'kansla', text_sv: 'Är det skam, trötthet eller längtan?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-07', bucket: 'kansla', text_sv: 'Vad behöver du mer än substans just nu?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-08', bucket: 'kansla', text_sv: 'Kan känslan få finnas utan handling?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-09', bucket: 'kansla', text_sv: 'Vad är sant just nu — tre fakta?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-KAN-10', bucket: 'kansla', text_sv: 'Vilken känsla vill du landa i efteråt?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-01', bucket: 'coping', text_sv: 'Vad fungerade senast suget gick över?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-02', bucket: 'coping', text_sv: 'Vilket coping-verktyg tar du nu — ett?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-03', bucket: 'coping', text_sv: 'Vem kan du nå med ett kort meddelande?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-04', bucket: 'coping', text_sv: 'Vad kan du göra i två minuter istället?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-05', bucket: 'coping', text_sv: 'Vilket If–Then gäller den här situationen?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-06', bucket: 'coping', text_sv: 'Behöver du vatten, mat eller rörelse först?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-07', bucket: 'coping', text_sv: 'Vill du andas, jorda eller urge surfa?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-08', bucket: 'coping', text_sv: 'Vad är det minsta steget som hjälper?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-09', bucket: 'coping', text_sv: 'Kan du byta rum eller plats?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-COP-10', bucket: 'coping', text_sv: 'Vilken distraktion känns minst tung?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-01', bucket: 'varde', text_sv: 'Vilket värdeord bär du de närmaste timmarna?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-02', bucket: 'varde', text_sv: 'Vad vill du stå för idag — ett ord?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-03', bucket: 'varde', text_sv: 'Hur tjänar nykterhet det som betyder mest?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-04', bucket: 'varde', text_sv: 'Vad skulle “bra nog” betyda just nu?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-05', bucket: 'varde', text_sv: 'Vilken riktning väljer du — inte vilket betyg?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-06', bucket: 'varde', text_sv: 'Vad är viktigt för dig som pappa/människa idag?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-07', bucket: 'varde', text_sv: 'Vilken frihet vill du skydda?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-08', bucket: 'varde', text_sv: 'Vad är du tacksam för i det lilla?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-09', bucket: 'varde', text_sv: 'Vilket mikrosteg matchar ditt värde?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-VAR-10', bucket: 'varde', text_sv: 'Om du lever dina värden i 1 timme — vad gör du?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-01', bucket: 'beredskap', text_sv: 'Om glidning: vad är steg 1 i din 15-minutersplan?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-02', bucket: 'beredskap', text_sv: 'Vilka tre högriskscenarier har du kartlagt?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-03', bucket: 'beredskap', text_sv: 'Vad är ditt If–Then för natt?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-04', bucket: 'beredskap', text_sv: 'Vem är din trygga kontakt-hint?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-05', bucket: 'beredskap', text_sv: 'Vad gör du om skam kommer efter ett slip?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-06', bucket: 'beredskap', text_sv: 'När ska du öppna SOS istället för att kämpa ensam?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-07', bucket: 'beredskap', text_sv: 'Vilken konsekvenskort-mening hjälper dig mest?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-08', bucket: 'beredskap', text_sv: 'Vad behöver uppdateras i din riskkarta?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-09', bucket: 'beredskap', text_sv: 'Hur vet du att det är dags att söka vårdstöd?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-BER-10', bucket: 'beredskap', text_sv: 'Vad firar du utan streak — en faktisk handling?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-001', text_sv: 'Vad behöver kroppen mest just nu?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-002', text_sv: 'Vilket verktyg är enklast att öppna?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-003', text_sv: 'Vad skulle trygg-du säga till dig?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-004', text_sv: 'Är det hungrig, arg, ensam eller trött?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-005', text_sv: 'Vad kan vänta femton minuter?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-006', text_sv: 'Vem är trygg att kontakta utan skuld?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-007', text_sv: 'Vilket rum gör dig lugnare?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-008', text_sv: 'Vad är nästa mikrosteg?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-009', text_sv: 'Vad vill suget att du ska tro?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-010', text_sv: 'Vad vet du som är sant istället?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-011', text_sv: 'Hur känns andningen i bröstet?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-012', text_sv: 'Vad är ett värdeord för idag?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-013', text_sv: 'Vad händer om du dricker vatten först?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-014', text_sv: 'Vilken riskplats kan du undvika just nu?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-015', text_sv: 'Vad skulle du göra för en vän i samma läge?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-016', text_sv: 'Behöver du sömn mer än lösning?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-017', text_sv: 'Vad är If–Then för den här triggern?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-018', text_sv: 'Kan du skjuta upp köpet till imorgon?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-019', text_sv: 'Vad är konsekvensen du faktiskt vill undvika?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-020', text_sv: 'Vilken känsla sitter under suget?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-021', text_sv: 'Vad fungerar som ankare för dig?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-022', text_sv: 'Behöver du ljus, mat eller rörelse?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-023', text_sv: 'Vad är tillräckligt bra för den här timmen?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-024', text_sv: 'Hur länge har vågen pågått?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-025', text_sv: 'Vad kan du lägga ifrån dig?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-026', text_sv: 'Vad är ett nej som skyddar dig?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-027', text_sv: 'Vad behöver du höra utan skam?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-028', text_sv: 'Kan du byta skärm till något lugnare?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-029', text_sv: 'Vad är planen efter urge surf?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-030', text_sv: 'Vem eller vad ger dig riktning?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-031', text_sv: 'Vad är ett litet bevis på att du klarar detta?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-032', text_sv: 'Vad triggade dig senast — plats, tid, känsla?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-033', text_sv: 'Vad kan du förbereda för kvällen?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-034', text_sv: 'Behöver du avsluta en konflikt eller pausa den?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-035', text_sv: 'Vad är din core why i en mening?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-036', text_sv: 'Kan du sätta en timer på tre minuter?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-037', text_sv: 'Vad är det snällaste du kan göra för dig nu?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-038', text_sv: 'Vad är risken med att bestämma i panik?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-039', text_sv: 'Vilket stödnummer finns under Stöd?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-040', text_sv: 'Vad skulle göra morgondagen lättare?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-041', text_sv: 'Är detta sug eller ensamhet?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-042', text_sv: 'Vad kan du fira utan rus?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-043', text_sv: 'Vad är ett tryggt alternativ till impulsen?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-044', text_sv: 'Hur känns fötterna mot golvet?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-045', text_sv: 'Vad behöver du släppa för i natt?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-046', text_sv: 'Kan buddy eller trygg person få ett SMS?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-047', text_sv: 'Vad är din anti-köp-mening?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-048', text_sv: 'Vad är nästa steg efter landning?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-049', text_sv: 'Vad påminner dig om att du är kapabel?', evidence_tier: 'product_copy' },
  { id: 'DF-Q-050', text_sv: 'Vad är ett mjukt ja till dig själv?', evidence_tier: 'product_copy' },
];

export const DF_QUESTION_COUNT = 100 as const;

export function dfQuestionDisplayText(q: DfQuestion): string {
  return sanitizeDfBankText(q.text_sv);
}
