import type { KampsparEntryRow, KbDocEntryRow } from '@/core/types/firestore';

export type ArchiveNode = {
  id: string;
  type: 'folder' | 'file';
  title: string;
  count?: number;
  isAutoGenerated?: boolean;
  children?: ArchiveNode[];
  date?: string;
  excerpt?: string;
  collection?: 'kampspar' | 'kb_docs';
  docId?: string;
};

type ArchiveSourceItem = {
  id: string;
  collection: 'kampspar' | 'kb_docs';
  title: string;
  excerpt: string;
  date: string;
  category: string;
  tags: string[];
};

const UNCategorized = 'Okategoriserat';

function slugify(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);
}

function formatArchiveDate(iso: string | null | undefined, fallback: string): string {
  if (iso && /^\d{4}-\d{2}-\d{2}/.test(iso)) return iso.slice(0, 10);
  if (fallback) return fallback.slice(0, 10);
  return '';
}

function excerptFromContent(content: string, max = 80): string {
  const trimmed = content.replace(/\s+/g, ' ').trim();
  if (!trimmed) return '';
  return trimmed.length > max ? `${trimmed.slice(0, max)}…` : trimmed;
}

function kampsparToItem(row: KampsparEntryRow): ArchiveSourceItem {
  const category = row.category?.trim() || row.entryType?.trim() || UNCategorized;
  const tags = (row.tags ?? []).map((t) => t.trim()).filter(Boolean);
  return {
    id: row.id,
    collection: 'kampspar',
    title: row.title.trim() || 'Namnlös post',
    excerpt: excerptFromContent(row.content),
    date: formatArchiveDate(row.eventDate, row.createdAt),
    category,
    tags,
  };
}

function kbDocToItem(row: KbDocEntryRow): ArchiveSourceItem {
  const category =
    row.inboxCategory?.trim() || row.folderId?.trim() || row.category?.trim() || UNCategorized;
  const tags = (row.inboxTags ?? row.tags ?? []).map((t) => t.trim()).filter(Boolean);
  return {
    id: row.id,
    collection: 'kb_docs',
    title: row.title.trim() || 'Namnlöst dokument',
    excerpt: excerptFromContent(row.content),
    date: formatArchiveDate(null, row.createdAt),
    category,
    tags,
  };
}

function fileNode(item: ArchiveSourceItem): ArchiveNode {
  return {
    id: `file-${item.collection}-${item.id}`,
    type: 'file',
    title: item.title,
    date: item.date || undefined,
    excerpt: item.excerpt || undefined,
    collection: item.collection,
    docId: item.id,
  };
}

function folderNode(id: string, title: string, children: ArchiveNode[]): ArchiveNode {
  const fileCount = countArchiveFiles(children);
  return {
    id,
    type: 'folder',
    title,
    count: fileCount,
    isAutoGenerated: true,
    children,
  };
}

/**
 * Mappar platta Kunskap-rader → hierarkiskt ArchiveNode-träd.
 * Gruppering: category → primär tag → fil. Inga hårdkodade mappar.
 */
export function mapFlatRowsToArchiveTree(
  kampspar: KampsparEntryRow[],
  kbDocs: KbDocEntryRow[] = [],
): ArchiveNode[] {
  const items = [...kampspar.map(kampsparToItem), ...kbDocs.map(kbDocToItem)];
  if (items.length === 0) return [];

  const byCategory = new Map<string, ArchiveSourceItem[]>();
  for (const item of items) {
    const bucket = byCategory.get(item.category) ?? [];
    bucket.push(item);
    byCategory.set(item.category, bucket);
  }

  const roots: ArchiveNode[] = [];

  for (const [category, categoryItems] of [...byCategory.entries()].sort(([a], [b]) =>
    a.localeCompare(b, 'sv'),
  )) {
    const catSlug = slugify(category) || 'okategoriserat';
    const tagGroups = new Map<string, ArchiveSourceItem[]>();
    const untagged: ArchiveSourceItem[] = [];

    for (const item of categoryItems) {
      const primaryTag = item.tags[0];
      if (primaryTag) {
        const bucket = tagGroups.get(primaryTag) ?? [];
        bucket.push(item);
        tagGroups.set(primaryTag, bucket);
      } else {
        untagged.push(item);
      }
    }

    const categoryChildren: ArchiveNode[] = [];

    if (tagGroups.size > 0) {
      for (const [tag, tagItems] of [...tagGroups.entries()].sort(([a], [b]) =>
        a.localeCompare(b, 'sv'),
      )) {
        const tagSlug = slugify(tag) || 'tagg';
        categoryChildren.push(
          folderNode(
            `folder-${catSlug}-${tagSlug}`,
            tag,
            tagItems
              .sort((a, b) => b.date.localeCompare(a.date))
              .map((item) => fileNode(item)),
          ),
        );
      }
    }

    if (untagged.length > 0) {
      categoryChildren.push(
        ...untagged
          .sort((a, b) => b.date.localeCompare(a.date))
          .map((item) => fileNode(item)),
      );
    }

    roots.push(folderNode(`folder-${catSlug}`, category, categoryChildren));
  }

  return roots;
}

export function filterArchiveTree(nodes: ArchiveNode[], query: string): ArchiveNode[] {
  const q = query.trim().toLowerCase();
  if (!q) return nodes;

  return nodes.reduce<ArchiveNode[]>((acc, node) => {
    if (node.type === 'file') {
      const haystack = `${node.title} ${node.excerpt ?? ''} ${node.date ?? ''}`.toLowerCase();
      if (haystack.includes(q)) acc.push(node);
      return acc;
    }

    const filteredChildren = filterArchiveTree(node.children ?? [], q);
    const folderMatch = node.title.toLowerCase().includes(q);
    if (folderMatch || filteredChildren.length > 0) {
      acc.push({ ...node, children: filteredChildren, count: countArchiveFiles(filteredChildren) });
    }
    return acc;
  }, []);
}

export function countArchiveFiles(nodes: ArchiveNode[]): number {
  return nodes.reduce((sum, node) => {
    if (node.type === 'file') return sum + 1;
    return sum + countArchiveFiles(node.children ?? []);
  }, 0);
}

/** Första två rotmappar — låg kognitiv belastning vid initial load. */
export function defaultExpandedFolderIds(tree: ArchiveNode[], max = 2): string[] {
  return tree
    .filter((n) => n.type === 'folder')
    .slice(0, max)
    .map((n) => n.id);
}
