import type { ThemePack } from './types';
import { THEME_SHARED_VARS } from './themeShared';
import { THEME_PACK_DESIGN } from './themePackDesign';
import { THEME_PACK_E_PROD } from './themePackE';
import { THEME_PACK_MOCKUP } from './themePackMockup';
import { THEME_PACK_K } from './themePackK';
import { THEME_PACK_REDESIGN_A } from './themePackRedesignA';
import { THEME_PACK_OBSIDIAN_DEPTH } from './themePackObsidianDepth';
import { THEME_PACK_REMIX_E_HAMN } from './themePackRemix';

const shared = THEME_SHARED_VARS;

export { THEME_SHARED_VARS } from './themeShared';

/** Canonical theme packs — add new cool themes here only. */
export const THEME_REGISTRY: ThemePack[] = [
  ...THEME_PACK_DESIGN,
  ...THEME_PACK_MOCKUP,
  THEME_PACK_E_PROD,
  {
    id: 'I-stone',
    label: 'Architect Stone',
    description: 'Svart sten, guld klocka, smart widget expanded.',
    background: 'texture-stone',
    preview: '/design/themes/I-architect-vault/00-smart-widget-expanded.png',
    cssVars: {
      ...shared,
      '--bg': '#0a0a0a',
      '--bg-dusk': '#121212',
      '--surface': '#111111',
      '--surface-2': '#1a1a1a',
      '--surface-3': '#222222',
      '--accent': '#d4af37',
      '--accent-secondary': '#f59e0b',
      '--accent-light': '#e8d48a',
      '--accent-glow': 'rgba(212, 175, 55, 0.18)',
      '--success': '#6b8f71',
      '--glass': 'rgba(8, 8, 8, 0.72)',
      '--glass-hero': 'rgba(8, 8, 8, 0.85)',
      '--border': 'rgba(212, 175, 55, 0.12)',
      '--border-strong': 'rgba(212, 175, 55, 0.45)',
      '--compass-disk': '#1a1a1a',
    },
  },
  {
    id: 'I-alchemical',
    label: 'Alchemical Gold',
    description: 'Marmor, glödande guld — Kompass, Rutiner, Budget.',
    background: 'texture-marble',
    preview: '/design/themes/I-architect-vault/02-alchemical-gold.png',
    cssVars: {
      ...shared,
      '--bg': '#050505',
      '--bg-dusk': '#0a0a0a',
      '--surface': '#0f0f0f',
      '--surface-2': '#161616',
      '--surface-3': '#1e1e1e',
      '--accent': '#e8c547',
      '--accent-secondary': '#f59e0b',
      '--accent-light': '#f5dfa0',
      '--accent-glow': 'rgba(232, 197, 71, 0.22)',
      '--success': '#6b8f71',
      '--glass': 'rgba(5, 5, 5, 0.78)',
      '--glass-hero': 'rgba(5, 5, 5, 0.88)',
      '--border': 'rgba(232, 197, 71, 0.14)',
      '--border-strong': 'rgba(232, 197, 71, 0.5)',
      '--compass-disk': '#1a1510',
    },
  },
  {
    id: 'I-skymning',
    label: 'Nordic Skymning',
    description: 'Aurora glass — MåBra, KBT (modul-scoped mint).',
    background: 'aurora',
    preview: '/design/themes/I-architect-vault/03-nordic-skymning.png',
    cssVars: {
      ...shared,
      '--bg': '#0a1614',
      '--bg-dusk': '#12151f',
      '--surface': '#0f1a18',
      '--surface-2': '#142220',
      '--surface-3': '#1a2b28',
      '--accent': '#4fd1c5',
      '--accent-secondary': '#2dd4bf',
      '--accent-light': '#99f6e4',
      '--accent-glow': 'rgba(79, 209, 197, 0.18)',
      '--success': '#2dd4bf',
      '--glass': 'rgba(10, 30, 35, 0.55)',
      '--glass-hero': 'rgba(10, 30, 35, 0.72)',
      '--border': 'rgba(79, 209, 197, 0.12)',
      '--border-strong': 'rgba(79, 209, 197, 0.28)',
      '--compass-disk': '#0d3b3b',
    },
  },
  {
    id: 'I-hamn',
    label: 'Trygg Hamn',
    description: 'Nautical guld — Hamn, kompassråd, lågaffektiv trygghet.',
    background: 'nautical',
    preview: '/design/themes/I-architect-vault/04-trygg-hamn.png',
    cssVars: {
      ...shared,
      '--bg': '#2c2f33',
      '--bg-dusk': '#23262a',
      '--surface': '#36393f',
      '--surface-2': '#3d4148',
      '--surface-3': '#454950',
      '--accent': '#d4af37',
      '--accent-secondary': '#c9a87c',
      '--accent-light': '#e8d48a',
      '--accent-glow': 'rgba(212, 175, 55, 0.15)',
      '--success': '#6b8f71',
      '--glass': 'rgba(44, 47, 51, 0.82)',
      '--glass-hero': 'rgba(44, 47, 51, 0.92)',
      '--border': 'rgba(212, 175, 55, 0.14)',
      '--border-strong': 'rgba(212, 175, 55, 0.35)',
      '--compass-disk': '#2a2d31',
    },
  },
  {
    id: 'I-glass',
    label: 'Dual Glass',
    description: 'Kompakt peek — Snabbanteckning + tyst inspelning.',
    background: 'texture-stone',
    preview: '/design/themes/I-architect-vault/01-glass-dual-actions.png',
    cssVars: {
      ...shared,
      '--bg': '#0a0a0a',
      '--bg-dusk': '#121212',
      '--surface': '#141010',
      '--surface-2': '#1a1510',
      '--surface-3': '#221c16',
      '--accent': '#d4af37',
      '--accent-secondary': '#f59e0b',
      '--accent-light': '#e8d48a',
      '--accent-glow': 'rgba(212, 175, 55, 0.25)',
      '--success': '#6b8f71',
      '--glass': 'rgba(20, 15, 10, 0.65)',
      '--glass-hero': 'rgba(20, 15, 10, 0.78)',
      '--border': 'rgba(212, 175, 55, 0.18)',
      '--border-strong': 'rgba(212, 175, 55, 0.55)',
      '--compass-disk': '#1a1410',
    },
  },
  {
    id: 'G-varm-hamn',
    label: 'Varm Hamn',
    description: 'Espresso, guld kompass, rose-gold — Barnfokus, KBT, Familjen.',
    background: 'texture-stone',
    preview: '/design/themes/G-varm-hamn/00-hero-livskompass.png',
    cssVars: {
      ...shared,
      '--bg': '#1a1410',
      '--bg-dusk': '#151008',
      '--surface': '#221c16',
      '--surface-2': '#2a2218',
      '--surface-3': '#332a1f',
      '--accent': '#d4af37',
      '--accent-secondary': '#c9a87c',
      '--accent-light': '#e8d48a',
      '--accent-glow': 'rgba(201, 168, 124, 0.2)',
      '--success': '#6b8f71',
      '--glass': 'rgba(26, 20, 16, 0.72)',
      '--glass-hero': 'rgba(26, 20, 16, 0.88)',
      '--border': 'rgba(201, 168, 124, 0.14)',
      '--border-strong': 'rgba(212, 175, 55, 0.4)',
      '--compass-disk': '#1a1410',
    },
  },
  // Theme Pack J — hub + widget (docs/design/themes/J-PACK-EIGHT-HUBS.md)
  {
    id: 'J-fyren-hem',
    label: 'Fyren Hem',
    description: 'Hem Kompass + Fyren W1/WH3 — stark guld glow på kant-widget.',
    background: 'texture-stone',
    preview: '/design/themes/I-architect-vault/00-smart-widget-expanded.png',
    cssVars: {
      ...shared,
      '--bg': '#0a0a0a',
      '--bg-dusk': '#121212',
      '--surface': '#111111',
      '--surface-2': '#1a1a1a',
      '--surface-3': '#222222',
      '--accent': '#d4af37',
      '--accent-secondary': '#f59e0b',
      '--accent-light': '#e8d48a',
      '--accent-glow': 'rgba(212, 175, 55, 0.28)',
      '--success': '#6b8f71',
      '--glass': 'rgba(8, 8, 8, 0.72)',
      '--glass-hero': 'rgba(8, 8, 8, 0.88)',
      '--border': 'rgba(212, 175, 55, 0.16)',
      '--border-strong': 'rgba(212, 175, 55, 0.5)',
      '--compass-disk': '#1a1a1a',
    },
  },
  {
    id: 'J-valv-pansar',
    label: 'Valv Pansar',
    description: 'Valv WORM + WH1 diskret inspelning — F guld pansar.',
    background: 'texture-stone',
    preview: '/design/themes/F-guld-pansar/05-pansaret-valv.png',
    cssVars: {
      ...shared,
      '--bg': '#080808',
      '--bg-dusk': '#0c0c0c',
      '--surface': '#0f0f0f',
      '--surface-2': '#141414',
      '--surface-3': '#1a1a1a',
      '--accent': '#c9a227',
      '--accent-secondary': '#d4af37',
      '--accent-light': '#e8d48a',
      '--accent-glow': 'rgba(201, 162, 39, 0.2)',
      '--success': '#6b8f71',
      '--glass': 'rgba(6, 6, 6, 0.8)',
      '--glass-hero': 'rgba(6, 6, 6, 0.92)',
      '--border': 'rgba(201, 162, 39, 0.14)',
      '--border-strong': 'rgba(201, 162, 39, 0.55)',
      '--compass-disk': '#141210',
    },
  },
  {
    id: 'J-planering-fyren',
    label: 'Planering Fyren',
    description: 'Kanban P3 + Projekt widget — alchemical amber.',
    background: 'texture-marble',
    preview: '/design/themes/F-guld-pansar/widget-bar.png',
    cssVars: {
      ...shared,
      '--bg': '#050505',
      '--bg-dusk': '#0a0a0a',
      '--surface': '#0f0f0f',
      '--surface-2': '#161616',
      '--surface-3': '#1e1e1e',
      '--accent': '#e8c547',
      '--accent-secondary': '#f59e0b',
      '--accent-light': '#f5dfa0',
      '--accent-glow': 'rgba(245, 158, 11, 0.22)',
      '--success': '#6b8f71',
      '--glass': 'rgba(5, 5, 5, 0.78)',
      '--glass-hero': 'rgba(5, 5, 5, 0.9)',
      '--border': 'rgba(232, 197, 71, 0.16)',
      '--border-strong': 'rgba(245, 158, 11, 0.45)',
      '--compass-disk': '#1a1510',
    },
  },
  {
    id: 'J-familjen-varm',
    label: 'Familjen Varm',
    description: 'Barnfokus + WH5 — espresso rose-gold (G).',
    background: 'texture-stone',
    preview: '/design/themes/G-varm-hamn/03-barnfokus.png',
    cssVars: {
      ...shared,
      '--bg': '#1a1410',
      '--bg-dusk': '#151008',
      '--surface': '#221c16',
      '--surface-2': '#2a2218',
      '--surface-3': '#332a1f',
      '--accent': '#d4af37',
      '--accent-secondary': '#c9a87c',
      '--accent-light': '#e8d48a',
      '--accent-glow': 'rgba(201, 168, 124, 0.22)',
      '--success': '#7ba383',
      '--glass': 'rgba(26, 20, 16, 0.74)',
      '--glass-hero': 'rgba(26, 20, 16, 0.9)',
      '--border': 'rgba(201, 168, 124, 0.16)',
      '--border-strong': 'rgba(212, 175, 55, 0.42)',
      '--compass-disk': '#1a1410',
    },
  },
  {
    id: 'J-hamn-greyrock',
    label: 'Hamn Grey Rock',
    description: 'Trygg hamn + WH4 BIFF — grafit, endast guld accent.',
    background: 'texture-stone',
    preview: '/design/themes/H-grafit-greyrock/02-trygg-hamn-hub.png',
    cssVars: {
      ...shared,
      '--bg': '#1c1c1e',
      '--bg-dusk': '#18181a',
      '--surface': '#2c2c2e',
      '--surface-2': '#323234',
      '--surface-3': '#3a3a3c',
      '--accent': '#d4af37',
      '--accent-secondary': '#c9a87c',
      '--accent-light': '#e8d48a',
      '--accent-glow': 'rgba(212, 175, 55, 0.12)',
      '--success': '#6b8f71',
      '--glass': 'rgba(28, 28, 30, 0.85)',
      '--glass-hero': 'rgba(28, 28, 30, 0.94)',
      '--border': 'rgba(212, 175, 55, 0.1)',
      '--border-strong': 'rgba(212, 175, 55, 0.32)',
      '--compass-disk': '#242426',
    },
  },
  {
    id: 'J-mabra-lavendel',
    label: 'MåBra Lavendel',
    description: 'Vit zon / Transformatorn — lavendel + guld (ej turkos).',
    background: 'texture-stone',
    preview: '/design/themes/G-varm-hamn/06-kbt-transformator.png',
    cssVars: {
      ...shared,
      '--bg': '#141018',
      '--bg-dusk': '#18141c',
      '--surface': '#1a1520',
      '--surface-2': '#221c28',
      '--surface-3': '#2a2430',
      '--accent': '#b8a9c9',
      '--accent-secondary': '#d4af37',
      '--accent-light': '#e8dff5',
      '--accent-glow': 'rgba(184, 169, 201, 0.18)',
      '--success': '#6b8f71',
      '--glass': 'rgba(20, 16, 24, 0.72)',
      '--glass-hero': 'rgba(20, 16, 24, 0.86)',
      '--border': 'rgba(184, 169, 201, 0.14)',
      '--border-strong': 'rgba(212, 175, 55, 0.38)',
      '--compass-disk': '#1e1824',
    },
  },
  {
    id: 'J-barnporten-ljus',
    label: 'Barnporten Ljus',
    description: 'Barn PWA 2×2 — cream, guld, mjuk nautical (plan).',
    background: 'nautical',
    preview: '/design/themes/G-varm-hamn/03-barnfokus.png',
    cssVars: {
      ...shared,
      '--bg': '#1e1814',
      '--bg-dusk': '#1a1612',
      '--surface': '#262018',
      '--surface-2': '#2e281e',
      '--surface-3': '#363024',
      '--accent': '#e8c547',
      '--accent-secondary': '#d4af37',
      '--accent-light': '#f5e6b8',
      '--accent-glow': 'rgba(232, 197, 71, 0.2)',
      '--success': '#7ba383',
      '--glass': 'rgba(30, 24, 20, 0.7)',
      '--glass-hero': 'rgba(30, 24, 20, 0.85)',
      '--border': 'rgba(232, 197, 71, 0.14)',
      '--border-strong': 'rgba(212, 175, 55, 0.4)',
      '--compass-disk': '#221c18',
    },
  },
  {
    id: 'J-vardagen-orbit',
    label: 'Vardagen Orbit',
    description: 'Kompasser, Kunskap, Arbetsliv, Ekonomi + WH2 anteckning.',
    background: 'texture-marble',
    preview: '/design/themes/I-architect-vault/02-alchemical-gold.png',
    cssVars: {
      ...shared,
      '--bg': '#050508',
      '--bg-dusk': '#08080c',
      '--surface': '#0c0c10',
      '--surface-2': '#121218',
      '--surface-3': '#181820',
      '--accent': '#e8c547',
      '--accent-secondary': '#d4af37',
      '--accent-light': '#f5dfa0',
      '--accent-glow': 'rgba(232, 197, 71, 0.2)',
      '--success': '#6b8f71',
      '--glass': 'rgba(5, 5, 8, 0.78)',
      '--glass-hero': 'rgba(5, 5, 8, 0.9)',
      '--border': 'rgba(232, 197, 71, 0.14)',
      '--border-strong': 'rgba(212, 175, 55, 0.48)',
      '--compass-disk': '#141418',
    },
  },
  // Theme Pack K — åtta nya varianter (docs/design/themes/K-PACK-EIGHT-VARIANTS.md)
  ...THEME_PACK_K,
  // Style A — Nordic Precision (rollback — Theme Lab)
  ...THEME_PACK_REDESIGN_A,
  // Remix B — Tema E + D1 chrome (prod default 2026-06-15)
  THEME_PACK_REMIX_E_HAMN,
  // Obsidian Depth — låst 3D shell (2026-06-14)
  ...THEME_PACK_OBSIDIAN_DEPTH,
];

export const DEFAULT_THEME_ID = 'R-E-hamn-remix';

/** Legacy Theme Lab ids → canonical pack id. */
export const THEME_ID_ALIASES: Record<string, string> = {
  'D4-flat-luxe': 'D4-flat-deluxe',
};

/** Theme Pack J — hub auto-mapping (when Auto modul themes is on). */
export const J_PACK_THEME_IDS = [
  'J-fyren-hem',
  'J-valv-pansar',
  'J-planering-fyren',
  'J-familjen-varm',
  'J-hamn-greyrock',
  'J-mabra-lavendel',
  'J-barnporten-ljus',
  'J-vardagen-orbit',
] as const;

export const THEME_BY_ID = Object.fromEntries(
  THEME_REGISTRY.map((t) => [t.id, t]),
) as Record<string, ThemePack>;

export function resolveThemeId(id: string): string {
  return THEME_ID_ALIASES[id] ?? id;
}

export function getTheme(id: string): ThemePack {
  const resolved = resolveThemeId(id);
  return THEME_BY_ID[resolved] ?? THEME_BY_ID[DEFAULT_THEME_ID];
}
