export { MainLayout } from './layout/MainLayout';
export { FloatingDock } from './layout/FloatingDock';
export { AmbientBackground } from './layout/AmbientBackground';
export { HubPageShell } from './layout/HubPageShell';
export { ModuleShell } from './layout/ModuleShell';
export { BentoCard } from './ui/BentoCard';
export { useStore } from './store';
export type { AppState, UiState, SystemState, User } from './store';
export { app, functions } from './firebase/init';
export { db, saveCheckIn, saveJournalEntry, saveVaultLog, saveChildrenLog } from './firebase/firestore';
export { AuthProvider, AuthGate, useZeroFootprint } from './auth';
export { AppRoutes } from './routing/AppRoutes';
export { HomePage } from './pages/HomePage';
export type { VaultLog, CheckIn, KnowledgeDoc, Routine } from './types/firestore';
export { FIRESTORE_COLLECTIONS } from './types/firestore';
